name: Android Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Configure Gradle heap size
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties

      - name: Run Gradle tests
        run: ./gradlew test --no-daemon --max-workers=2 --info

      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon --max-workers=2 --info

      - name: Upload unsigned release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-release-apk
          path: app/build/outputs/apk/release/app-release.apk
